### ISSUE TITLE
major class dominates loss for binary segmentation

### ISSUE THREAD

**Issue by chuckgu** [lwye/CMSA-Net#1]
hi

I'm so impressed your work in this repo.

Usually, it's hard to optimize an imbalanced binary segmentation task only using BCE loss due to class domination.

if you used some methods to block the class domination issue, can you give us a tip?

thanks in advance.

**Comment by lwye** [comment]
Hi,

You can add weights for classes to balance the cost of BCE loss. One straightforward way is to use the proportion of each class as the weight.

**Comment by chuckgu** [comment]
Thank you for your quick response.

In this repo, I was not able to find any lines to add weights for an minor class.

As far as I know, you set equal weights for positive and negative classes.

Did I miss something? or Did it work well without adding weights in this repo?

**Comment by lwye** [comment]
https://github.com/lwye/CMSA-Net/blob/8fc9feea4f7bf20eabdf29125a927208b4cca114/CMSA_model.py#L232

Here defines weights for the loss.

**Comment by chuckgu** [comment]
Yes, I know that line and understood that you equally set weights 1,1 for positive and negative classes which means no weights here. Am I right?

If right, it looks great to optimize imbalanced set well.

Thank you again for your quick response.

**Comment by lwye** [comment]
Yes, you are right. It works for RIS task in the paper. Changing weights doesn't show much difference.
